# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sampleCallkit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sampleCallkit
  pod 'EnxRTCiOS', '2.3.16'
   pod 'Socket.IO-Client-Swift', '~> 15.2.0'
  pod 'NWPusher', '~> 0.7.0'
  pod 'ReachabilitySwift'
  pod 'SVProgressHUD'

  target 'sampleCallkitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sampleCallkitUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
post_install do |installer|
        installer.generated_projects.each do |project|
              project.targets.each do |target|
                  target.build_configurations.each do |config|
                      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
                   end
              end
       end
    end

end
