# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sampleCallkit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sampleCallkit
  pod 'GoogleWebRTC', '1.1.29229'
  pod 'Socket.IO-Client-Swift', '~> 15.0.0'
  #pod 'Firebase/Messaging'
  # pod 'Firebase/Analytics'
  pod 'NWPusher', '~> 0.7.0'

  target 'sampleCallkitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sampleCallkitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
