# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sampleCallkit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sampleCallkit

   pod 'Socket.IO-Client-Swift', '~> 16.1.1'
  pod 'NWPusher', '~> 0.7.0'
  pod 'ReachabilitySwift'
  pod 'SVProgressHUD'

  target 'sampleCallkitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sampleCallkitUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  


end
